// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_SOURCE_UNKNOWN   SourceType = 0
	SourceType_SOURCE_POSTGRES  SourceType = 1
	SourceType_SOURCE_MYSQL     SourceType = 2
	SourceType_SOURCE_SQLSERVER SourceType = 3
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_POSTGRES",
		2: "SOURCE_MYSQL",
		3: "SOURCE_SQLSERVER",
	}
	SourceType_value = map[string]int32{
		"SOURCE_UNKNOWN":   0,
		"SOURCE_POSTGRES":  1,
		"SOURCE_MYSQL":     2,
		"SOURCE_SQLSERVER": 3,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_event_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_pb_event_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_pb_event_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_UNKNOWN Action = 0
	Action_INSERT  Action = 1
	Action_UPDATE  Action = 2
	Action_DELETE  Action = 3
	Action_COMMIT  Action = 4
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "UNKNOWN",
		1: "INSERT",
		2: "UPDATE",
		3: "DELETE",
		4: "COMMIT",
	}
	Action_value = map[string]int32{
		"UNKNOWN": 0,
		"INSERT":  1,
		"UPDATE":  2,
		"DELETE":  3,
		"COMMIT":  4,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_event_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_pb_event_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_pb_event_proto_rawDescGZIP(), []int{1}
}

type Checkpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Offset:
	//
	//	*Checkpoint_Lsn
	Offset        isCheckpoint_Offset `protobuf_oneof:"offset"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_pb_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pb_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_pb_event_proto_rawDescGZIP(), []int{0}
}

func (x *Checkpoint) GetOffset() isCheckpoint_Offset {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *Checkpoint) GetLsn() uint64 {
	if x != nil {
		if x, ok := x.Offset.(*Checkpoint_Lsn); ok {
			return x.Lsn
		}
	}
	return 0
}

type isCheckpoint_Offset interface {
	isCheckpoint_Offset()
}

type Checkpoint_Lsn struct {
	Lsn uint64 `protobuf:"varint,1,opt,name=lsn,proto3,oneof"`
}

func (*Checkpoint_Lsn) isCheckpoint_Offset() {}

type ChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceType    SourceType             `protobuf:"varint,1,opt,name=source_type,json=sourceType,proto3,enum=pb.SourceType" json:"source_type,omitempty"`
	Action        Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	Schema        string                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	KeyNames      []string               `protobuf:"bytes,5,rep,name=key_names,json=keyNames,proto3" json:"key_names,omitempty"`
	Before        []byte                 `protobuf:"bytes,6,opt,name=before,proto3" json:"before,omitempty"`
	After         []byte                 `protobuf:"bytes,7,opt,name=after,proto3" json:"after,omitempty"`
	Offset        *Checkpoint            `protobuf:"bytes,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_pb_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_pb_event_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeEvent) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_UNKNOWN
}

func (x *ChangeEvent) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_UNKNOWN
}

func (x *ChangeEvent) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ChangeEvent) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChangeEvent) GetKeyNames() []string {
	if x != nil {
		return x.KeyNames
	}
	return nil
}

func (x *ChangeEvent) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ChangeEvent) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ChangeEvent) GetOffset() *Checkpoint {
	if x != nil {
		return x.Offset
	}
	return nil
}

var File_pb_event_proto protoreflect.FileDescriptor

const file_pb_event_proto_rawDesc = "" +
	"\n" +
	"\x0epb/event.proto\x12\x02pb\"*\n" +
	"\n" +
	"Checkpoint\x12\x12\n" +
	"\x03lsn\x18\x01 \x01(\x04H\x00R\x03lsnB\b\n" +
	"\x06offset\"\x83\x02\n" +
	"\vChangeEvent\x12/\n" +
	"\vsource_type\x18\x01 \x01(\x0e2\x0e.pb.SourceTypeR\n" +
	"sourceType\x12\"\n" +
	"\x06action\x18\x02 \x01(\x0e2\n" +
	".pb.ActionR\x06action\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\x12\x1b\n" +
	"\tkey_names\x18\x05 \x03(\tR\bkeyNames\x12\x16\n" +
	"\x06before\x18\x06 \x01(\fR\x06before\x12\x14\n" +
	"\x05after\x18\a \x01(\fR\x05after\x12&\n" +
	"\x06offset\x18\b \x01(\v2\x0e.pb.CheckpointR\x06offset*]\n" +
	"\n" +
	"SourceType\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSOURCE_POSTGRES\x10\x01\x12\x10\n" +
	"\fSOURCE_MYSQL\x10\x02\x12\x14\n" +
	"\x10SOURCE_SQLSERVER\x10\x03*E\n" +
	"\x06Action\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06INSERT\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x04B\vZ\tmy-cdc/pbb\x06proto3"

var (
	file_pb_event_proto_rawDescOnce sync.Once
	file_pb_event_proto_rawDescData []byte
)

func file_pb_event_proto_rawDescGZIP() []byte {
	file_pb_event_proto_rawDescOnce.Do(func() {
		file_pb_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_event_proto_rawDesc), len(file_pb_event_proto_rawDesc)))
	})
	return file_pb_event_proto_rawDescData
}

var file_pb_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_event_proto_goTypes = []any{
	(SourceType)(0),     // 0: pb.SourceType
	(Action)(0),         // 1: pb.Action
	(*Checkpoint)(nil),  // 2: pb.Checkpoint
	(*ChangeEvent)(nil), // 3: pb.ChangeEvent
}
var file_pb_event_proto_depIdxs = []int32{
	0, // 0: pb.ChangeEvent.source_type:type_name -> pb.SourceType
	1, // 1: pb.ChangeEvent.action:type_name -> pb.Action
	2, // 2: pb.ChangeEvent.offset:type_name -> pb.Checkpoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_event_proto_init() }
func file_pb_event_proto_init() {
	if File_pb_event_proto != nil {
		return
	}
	file_pb_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Checkpoint_Lsn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_event_proto_rawDesc), len(file_pb_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_event_proto_goTypes,
		DependencyIndexes: file_pb_event_proto_depIdxs,
		EnumInfos:         file_pb_event_proto_enumTypes,
		MessageInfos:      file_pb_event_proto_msgTypes,
	}.Build()
	File_pb_event_proto = out.File
	file_pb_event_proto_goTypes = nil
	file_pb_event_proto_depIdxs = nil
}
